services:
  pb:
    build: ./pb
    volumes:
     - db-data:/pb/pb_data
    ports:
      - "8090:8090"
    working_dir: /app/pb
    networks:
      - back-front
  
  grafana:
    image: grafana/grafana-oss
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
    ports:
     - "3000:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
     - db-data:/data_from_pb_service

  sk:
    build: sk/
    image: htt-front:latest
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Paris
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - back-front

volumes:
  db-data:
  grafana-storage:

networks:
  back-front: