services:
  nginx:
    build: nginx/
    ports:
        - 80:80
    # restart: always
    networks:
      - the-network

  pb:
    build: pb/
    depends_on:
      - nginx
    volumes:
     - db-data:/pb/pb_data
    # ports: # MANAGED BY NGINX
    #   - "3002:8090"
    working_dir: /app/pb
    networks:
      - the-network
  
  grafana:
    image: grafana/grafana-oss
    depends_on:
      - nginx
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
      GF_SERVER_ROOT_URL: http://%(domain)s/grafana/
    # ports: # MANAGED BY NGINX
    #  - "3001:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
     - db-data:/data_from_pb_service
    networks:
      - the-network

  sk:
    build: sk/
    depends_on:
      - nginx
    image: htt-front:latest
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Paris
    restart: unless-stopped
    # ports: # MANAGED BY NGINX
    #   - 3000:3000
    networks:
      - the-network

volumes:
  db-data:
  grafana-storage:

networks:
  the-network: